In [0]:
df=spark.read.csv('/FileStore/tables/ratings-1.csv',header=True)
df

Out[1]: DataFrame[userId: string, movieId: string, rating: string, timestamp: string]

In [0]:
df=df.toPandas()
df

,userId,movieId,rating,timestamp
0,1,1,4.0,964982703
1,1,3,4.0,964981247
2,1,6,4.0,964982224
3,1,47,5.0,964983815
4,1,50,5.0,964982931
...,...,...,...,...
100831,610,166534,4.0,1493848402
100832,610,168248,5.0,1493850091
100833,610,168250,5.0,1494273047
100834,610,168252,5.0,1493846352
100835,610,170875,3.0,1493846415

In [0]:
# df2=df.drop('timestamp',axis=1)
# df2

In [0]:
print((df['userId'] == 1).sum())

100836

In [0]:
df.drop('timestamp',axis=1,inplace=True)

In [0]:
len(df.userId.unique())

Out[51]: 610

In [0]:
len(df.movieId.unique())

Out[6]: 9724

In [0]:
user_movie_df=df.pivot(index='userId',columns='movieId',values='rating') #we are interchanging rows and columns because we are finding item based similarity

In [0]:
user_movie_df.iloc[0:5,0:10]

movieId,1,10,100,100044,100068,100083,100106,100159,100163,100194
userId,,,,,,,,,,
1,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [0]:
user_movie_df.fillna(0,inplace=True)

In [0]:
user_movie_df

movieId,1,10,100,100044,100068,100083,100106,100159,100163,100194,...,99750,99764,998,99813,99846,99853,999,99910,99917,99992
userId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
101,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
102,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96,5.0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98,4.5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99,0,4.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [0]:
from sklearn.metrics import pairwise_distances

user_sim=1-pairwise_distances(user_movie_df.values,metric='cosine') #cosine gives opposite answer , so we use 1-

In [0]:
import pandas as pd

#convert it to df for better understanding 
user_sim_df=pd.DataFrame(user_sim,index=df.userId.unique(),columns=df.userId.unique())

In [0]:
user_sim_df

,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
1,1.000000,0.016875,0.147763,0.141447,0.156466,0.211480,0.121173,0.090142,0.019425,0.066894,...,0.051841,0.334727,0.028767,0.232766,0.110082,0.178069,0.282780,0.086557,0.062187,0.066231
2,0.016875,1.000000,0.090474,0.020533,0.036215,0.116766,0.178308,0.149245,0.133146,0.003137,...,0.000000,0.055251,0.016773,0.029036,0.038062,0.042865,0.018888,0.057771,0.130223,0.020587
3,0.147763,0.090474,1.000000,0.070894,0.142033,0.136122,0.178267,0.065328,0.000000,0.098179,...,0.015134,0.189074,0.000000,0.122328,0.124926,0.093664,0.071043,0.078111,0.053039,0.079063
4,0.141447,0.020533,0.070894,1.000000,0.026755,0.105728,0.045393,0.065297,0.000000,0.000000,...,0.000000,0.133919,0.000000,0.012955,0.000000,0.070774,0.107449,0.103712,0.000000,0.000000
5,0.156466,0.036215,0.142033,0.026755,1.000000,0.094133,0.087527,0.051458,0.029935,0.353838,...,0.000000,0.259438,0.000000,0.219928,0.586507,0.046217,0.136751,0.048376,0.054637,0.428520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.178069,0.042865,0.093664,0.070774,0.046217,0.184223,0.125659,0.142743,0.044271,0.000000,...,0.061351,0.265121,0.023369,0.091787,0.054546,1.000000,0.208704,0.089793,0.054944,0.023075
607,0.282780,0.018888,0.071043,0.107449,0.136751,0.177743,0.087595,0.083746,0.021467,0.130466,...,0.044602,0.271696,0.000000,0.240489,0.204494,0.208704,1.000000,0.144190,0.057705,0.072585
608,0.086557,0.057771,0.078111,0.103712,0.048376,0.102086,0.048995,0.141125,0.075348,0.000000,...,0.000000,0.150644,0.000000,0.045750,0.044044,0.089793,0.144190,1.000000,0.080515,0.000000
609,0.062187,0.130223,0.053039,0.000000,0.054637,0.143027,0.129430,0.163750,0.060405,0.019877,...,0.028132,0.131384,0.000000,0.048703,0.043413,0.054944,0.057705,0.080515,1.000000,0.000000
610,0.066231,0.020587,0.079063,0.000000,0.428520,0.055889,0.046604,0.022752,0.032758,0.368211,...,0.000000,0.166036,0.000000,0.167871,0.441116,0.023075,0.072585,0.000000,0.000000,1.000000

In [0]:
#all diagonal user is similar to itself , so it is of no use

import numpy as np

np.fill_diagonal(user_sim,0)

In [0]:
user_sim_df

,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
1,0.000000,0.016875,0.147763,0.141447,0.156466,0.211480,0.121173,0.090142,0.019425,0.066894,...,0.051841,0.334727,0.028767,0.232766,0.110082,0.178069,0.282780,0.086557,0.062187,0.066231
2,0.016875,0.000000,0.090474,0.020533,0.036215,0.116766,0.178308,0.149245,0.133146,0.003137,...,0.000000,0.055251,0.016773,0.029036,0.038062,0.042865,0.018888,0.057771,0.130223,0.020587
3,0.147763,0.090474,0.000000,0.070894,0.142033,0.136122,0.178267,0.065328,0.000000,0.098179,...,0.015134,0.189074,0.000000,0.122328,0.124926,0.093664,0.071043,0.078111,0.053039,0.079063
4,0.141447,0.020533,0.070894,0.000000,0.026755,0.105728,0.045393,0.065297,0.000000,0.000000,...,0.000000,0.133919,0.000000,0.012955,0.000000,0.070774,0.107449,0.103712,0.000000,0.000000
5,0.156466,0.036215,0.142033,0.026755,0.000000,0.094133,0.087527,0.051458,0.029935,0.353838,...,0.000000,0.259438,0.000000,0.219928,0.586507,0.046217,0.136751,0.048376,0.054637,0.428520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.178069,0.042865,0.093664,0.070774,0.046217,0.184223,0.125659,0.142743,0.044271,0.000000,...,0.061351,0.265121,0.023369,0.091787,0.054546,0.000000,0.208704,0.089793,0.054944,0.023075
607,0.282780,0.018888,0.071043,0.107449,0.136751,0.177743,0.087595,0.083746,0.021467,0.130466,...,0.044602,0.271696,0.000000,0.240489,0.204494,0.208704,0.000000,0.144190,0.057705,0.072585
608,0.086557,0.057771,0.078111,0.103712,0.048376,0.102086,0.048995,0.141125,0.075348,0.000000,...,0.000000,0.150644,0.000000,0.045750,0.044044,0.089793,0.144190,0.000000,0.080515,0.000000
609,0.062187,0.130223,0.053039,0.000000,0.054637,0.143027,0.129430,0.163750,0.060405,0.019877,...,0.028132,0.131384,0.000000,0.048703,0.043413,0.054944,0.057705,0.080515,0.000000,0.000000
610,0.066231,0.020587,0.079063,0.000000,0.428520,0.055889,0.046604,0.022752,0.032758,0.368211,...,0.000000,0.166036,0.000000,0.167871,0.441116,0.023075,0.072585,0.000000,0.000000,0.000000

In [0]:
user_sim_df.idxmax(axis=1)

Out[16]: 1      186
2       67
3      287
4      547
5      460
      ...
606    228
607    439
608    333
609    559
610     36
Length: 610, dtype: object

In [0]:
user_sim_df.iloc[0:1,260:270]

,261,262,263,264,265,266,267,268,269,270
1,0.02438,0.155269,0.168643,0.193167,0.105097,0.071705,0.116093,0.083544,0.120511,0.043659

In [0]:
movie_df=spark.read.csv('/FileStore/tables/movies.csv',header=True)

In [0]:
movie_df=movie_df.toPandas()
movie_df

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [0]:
movie_df.drop('genres', axis=1, inplace=True)

In [0]:
movie_df

,movieId,title
0,1,Toy Story (1995)
1,2,Jumanji (1995)
2,3,Grumpier Old Men (1995)
3,4,Waiting to Exhale (1995)
4,5,Father of the Bride Part II (1995)
...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017)
9738,193583,No Game No Life: Zero (2017)
9739,193585,Flint (2017)
9740,193587,Bungo Stray Dogs: Dead Apple (2018)
9741,193609,Andrew Dice Clay: Dice Rules (1991)

In [0]:
common_movies=df[df.userId==5].merge(df[df.userId==470],on='movieId')
common_movies.merge(movie_df,on='movieId')
common_movies

In [0]:
df

,userId,movieId,rating
0,1,1,4.0
1,1,3,4.0
2,1,6,4.0
3,1,47,5.0
4,1,50,5.0
...,...,...,...
100831,610,166534,4.0
100832,610,168248,5.0
100833,610,168250,5.0
100834,610,168252,5.0
100835,610,170875,3.0

[]
[]

,userId,movieId,rating
0,1,1,4.0
1,1,3,4.0
2,1,6,4.0
3,1,47,5.0
4,1,50,5.0
...,...,...,...
100831,610,166534,4.0
100832,610,168248,5.0
100833,610,168250,5.0
100834,610,168252,5.0
100835,610,170875,3.0

In [0]:
print((df['userId'] == 5).sum())

0

In [0]:
print(count(df.userId==5))

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
File <command-1072275833947665>:1
----> 1 print(count(df.userId==5))

NameError: name 'count' is not defined

In [0]:
%r 

myString <-"Hello Vinesh "
print(myString)

[1] "Hello Vinesh "